Feature/dynamiclinks
UCL/frrant pull request #349
Opened 2022-09-06 10:04 UTC by acholyn

Closes #202, includes tests

2022-09-08 15:25 UTC, tcouch commented
@acholyn I think it's be good if we could do the same thing for work searches as we've done for bibliography items; i.e. create an annotation that combines antiquarian name and work name and search that.

2022-09-13 09:04 UTC, acholyn commented
The annotation method could be extracted into its own function but I've opted to just add the work search as another function

2022-09-13 10:42 UTC, tcouch requested changes

2022-09-13 10:42 UTC, tcouch commented on src/rard/research/views/mention.py
> +        )
I noticed authors just uses the antiquarian's order name (e.g. Accius for Lucius Accius). That means if you do a work search for `@wk:lucius` it won't show any of Accius's works. We can get the whole name by copying the pattern used by the WorkManager which uses StringAgg to add the authors annotation, but use antiquarian__name instead.

```suggestion
        qs = Work.objects.annotate(
            author_title=Concat(
                StringAgg("antiquarian__name", delimiter=","),
                Value(" "),
                F("name"),
                output_field=CharField()
            )
        )
```

2022-09-13 10:42 UTC, tcouch commented on src/rard/research/views/mention.py
> +from django.db.models import CharField, F, Q, Value
Import StringAgg (see suggestion below)
```suggestion
from django.db.models import CharField, F, Q, Value
from django.contrib.postgres.aggregates import StringAgg
```

2022-09-13 10:42 UTC, tcouch commented on src/rard/research/tests/views/test_mentions.py
> +        self.assertEqual(len(list(view.get_queryset())), 3)
I don't think the number search is necessary here, but what's missing is a test to see if we're matching work authors' names. If you add works to antiquarians in the setup function we can test that here; e.g. "and" should match antiquarian "Andrew" and work "andropov"

2022-09-13 10:42 UTC, tcouch commented on src/rard/research/tests/views/test_mentions.py
> +    def test_bibliography_search(self):
I can't see any examples here where you try to match the contents of bibliography titles. It'd be good to test for something that matches across both fields on different objects; e.g. "two" matching bi 2 and bi3 if the title for bi3 was "peppers two apples"

2022-09-13 12:10 UTC, acholyn commented on src/rard/research/views/mention.py
> +        )
oh nice, thanks!

2022-09-13 14:55 UTC, tcouch commented
Great. I think this looks good now.

2022-09-21 14:26 UTC, merged