Feature/move links between works
UCL/frrant pull request #415
Opened 2024-01-16 12:08 UTC by acholyn

closes #380

2024-01-30 17:19 UTC, tcouch requested changes
At the moment, if a user clicks update on the form, but hasn't selected a book, nothing appears to happen. Behind the scenes you get an error message because not book can be found. I think either the form should be returned with a helpful error message, or the submit button should be disabled until both a work and book have been selected.

2024-01-30 17:19 UTC, tcouch commented on src/rard/templates/research/partials/render_inline_worklink_form.html
I think this should go in `templates/research/inline_forms`

2024-01-30 17:19 UTC, tcouch commented on src/rard/research/forms.py
> +                book = Book.objects.get(pk=kwargs["data"]["book"])
Can you check if a book id is returned first?

2024-01-30 19:04 UTC, acholyn commented
ah - how it worked previously was that if no book was selected it automatically assigned the unknown one of that work. I didn't realise this had stopped being the case - should I make it so again? If not I'll disable the submit

2024-01-30 20:50 UTC, tcouch commented
Yeah, defaulting to unknown sounds sensible. I suppose in that case, there's no reason to have the none option?

2024-01-30 20:55 UTC, acholyn commented
I think without having the blank it chooses the first option (which would be an actual book) so that wouldn't work. I could change it to say unknown? It wouldn't have a value and would mean unknown shows up twice (if I remember correctly)

2024-02-07 12:55 UTC, tcouch approved these changes

2024-02-07 13:07 UTC, merged