Feature/consolidating edit menu
UCL/frrant pull request #442
Opened 2024-03-14 16:26 UTC by acholyn

closes #434 and #447
---
The `Edit` menu has been rejigged to better display options and complete actions without having to require an editing lock. This helps bring more consistency and reduces the code volume.

- Deletion, conversion and duplication are available where relevant without needing a lock and are available when there is a lock
- locking editing is available from the same menu as a dropdown 

Below are screengrabs:

(unlinked) fragment without editing lock:
<img width="259" alt="image" src="https://github.com/UCL/frrant/assets/72266023/bdc58824-e002-464a-bba2-cfc1f9269565">

when editing:
<img width="237" alt="image" src="https://github.com/UCL/frrant/assets/72266023/44d25460-7ede-4b29-92c4-4171caeaf943">

testimonia, works and antiquarians when editing:
<img width="211" alt="image" src="https://github.com/UCL/frrant/assets/72266023/b5f44c69-ad05-4ce8-9a91-e882e90b1de5">

anonymous without editing lock:
<img width="280" alt="image" src="https://github.com/UCL/frrant/assets/72266023/1ee743bf-97a6-41e6-807b-ba4a68595d69">

2024-03-20 08:51 UTC, tcouch requested changes
A few bugs here:
* I couldn't get Delete to work with or without an editing lock in place
* Warnings don't show up for make anonymous/unlinked or duplicate
* If no lock is in place, when you click make anonymous/unlinked you get a message saying you can't because there's no lock

You're not going to be happy with me but I think it might be better if we just have the consolidated 'Actions' menu in edit mode, and keep the original 'Edit' menu for when there isn't a lock.

2024-03-20 12:19 UTC, acholyn commented
I don't think we have any duplication warnings set up
Shall the menu be "edit" as before (when no lock) or still actions > edit

2024-03-21 13:02 UTC, acholyn commented
To do:
change it back so that the options are only available when there's a lock

2024-05-02 12:19 UTC, acholyn commented
need to up
date so testimonia have the option for duplication and update unlinked with option to convert to testimonium

2024-06-18 08:57 UTC, merged