closes #471
UCL/frrant pull request #474
Opened 2024-08-21 14:56 UTC by acholyn

Should fix issue as the OT shouldn't have any ap crit items on creation

2025-01-08 11:06 UTC, tcouch requested changes

2025-01-08 11:06 UTC, tcouch commented on src/rard/research/forms.py
> +                self.fields["content"].widget.attrs["class"] = "enableApparatusCriticus"
I haven't tested this in practice, but won't this set the class to "enableApparatusCriticus" rather than "enableCKEditor enableApparatusCriticus" if there any apparatus criticus items? If so, I'd expect the editor not to get initialised. Likewise for OriginalTextForm below.

2025-01-08 11:33 UTC, acholyn commented on src/rard/research/forms.py
> +                self.fields["content"].widget.attrs["class"] = "enableApparatusCriticus"
ah, can we use += or will we just have to repeat the ckeditor string?

2025-01-08 13:43 UTC, tcouch commented on src/rard/research/forms.py
> +                ] += "enableApparatusCriticus"
You'll need a space
```suggestion
                ] += " enableApparatusCriticus"
```

2025-01-08 13:44 UTC, tcouch commented on src/rard/research/forms.py
> +                ] += "enableApparatusCriticus"
```suggestion
                ] += " enableApparatusCriticus"
```

2025-01-08 13:49 UTC, tcouch commented on src/rard/research/forms.py
>              if original_text.apparatus_criticus_items.count() > 0:
Is there a reason this needs to come before the call to super().__init__ ? Just that it probably makes sense to follow the same order as above where `ennableApparatusCriticus` is added to the class list after `enableCKEditor`. Also I don't know if += would work here if widget.attrs["class"] potentially doesn't exist as a key yet. Have you tested it?

2025-01-08 13:56 UTC, tcouch commented on src/rard/research/forms.py
>              if original_text.apparatus_criticus_items.count() > 0:
Ah yeah, the failing pytest check seems to confirm this.

2025-01-10 16:42 UTC, tcouch approved these changes

2025-01-14 09:44 UTC, merged